### ISSUE TITLE
How to analysis different compartments from two sampales

### ISSUE THREAD

**Issue by Zheng19w** [ilead-cong/hic_down#2]
I have two different tissue samples which have been sequenced by Hic respectively. I would like to know how to compare the changes at these two samples, which compartment is from AtoB, which compartment is from BtoA and which compartment is unchanged

**Comment by ilead-cong** [comment]
Sorry, hic_down do not have this function. But, I think dcHiC(https://github.com/ay-lab/dcHiC) can solve your problem.

**Comment by Zheng19w** [comment]
thank you very much



---- Replied Message ----
| From | ***@***.***> |
| Date | 01/10/2023 00:01 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [ilead-cong/hic_down] How to analysis different compartments from two sampales (Issue #2) |

Sorry, hic_down do not have this function. But, I think dcHiC(https://github.com/ay-lab/dcHiC) can solve your problem.

**Comment by Zheng19w** [comment]
Thank you for your reply. I have another question, should we use hicpro or juicer for upstream analysis


thank you very much



---- Replied Message ----
| From | ***@***.***> |
| Date | 01/10/2023 00:01 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [ilead-cong/hic_down] How to analysis different compartments from two sampales (Issue #2) |

Sorry, hic_down do not have this function. But, I think dcHiC(https://github.com/ay-lab/dcHiC) can solve your problem.

**Comment by ilead-cong** [comment]
I think it is possible, but the specific upstream analysis is related to the HiC experiment. For example, my HiC experiment is DLOHIC (DIO:10.1038/s41588-018-0111-2), so the tool used for upstream analysis is DLO-HiC-Tools (https://github.com/GangCaoLab/DLO-HiC-Tools)

**Comment by Zheng19w** [comment]
haha，Thank you for your letter. I think we are alumni. I am also a PhD student in Huazhong Agricultural University.



---- Replied Message ----
| From | ***@***.***> |
| Date | 01/10/2023 00:23 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [ilead-cong/hic_down] How to analysis different compartments from two sampales (Issue #2) |

I think it is possible, but the specific upstream analysis is related to the HiC experiment. For example, my HiC experiment is DLOHIC (DIO:10.1038/s41588-018-0111-2), so the tool used for upstream analysis is DLO-HiC-Tools (https://github.com/GangCaoLab/DLO-HiC-Tools)

**Comment by Zheng19w** [comment]
I wonder if I can use hicpro to connect with hicdown well


haha，Thank you for your letter. I think we are alumni. I am also a PhD student in Huazhong Agricultural University.



---- Replied Message ----
| From | ***@***.***> |
| Date | 01/10/2023 00:23 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [ilead-cong/hic_down] How to analysis different compartments from two sampales (Issue #2) |

I think it is possible, but the specific upstream analysis is related to the HiC experiment. For example, my HiC experiment is DLOHIC (DIO:10.1038/s41588-018-0111-2), so the tool used for upstream analysis is DLO-HiC-Tools (https://github.com/GangCaoLab/DLO-HiC-Tools)

**Comment by ilead-cong** [comment]
I think it's okay. The pair file format is a commonly used data format in HIC.

Coincidentally, I am currently studying at Huazhong Agricultural University and will graduate in June this year.

**Comment by Zheng19w** [comment]
Congratulations and thank you for your reply



---- Replied Message ----
| From | ***@***.***> |
| Date | 01/10/2023 00:38 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [ilead-cong/hic_down] How to analysis different compartments from two sampales (Issue #2) |

I think it's okay. The pair file format is a commonly used data format in HIC.

Coincidentally, I am currently studying at Huazhong Agricultural University and will graduate in June this year.

**Comment by Zheng19w** [comment]
Hello, can I add you a wechat? my wechat number is 13183836357 ，I have a few questions about hic_down, I'd like to ask you

**Comment by Zheng19w** [comment]
I want to know what form of matrix Hic_down requires input, now that I have obtained valid.pairs through hicpro,Next, I will convert the.hic file through hicprotojuicer.sh. Can it be used as the input file

**Comment by ilead-cong** [comment]
I'm very sorry, I'm in the stage of graduating and looking for a job recently, very busy and anxious, I didn't pay attention to check the mailbox. Two file type: pair.gz is for loop, mcool is for TAD and ABcompartment. And, mcool can be obtained through pair file conversion. You can also directly refer to the commands of the package I use, it is also possible not to use this process.

**Comment by Zheng19w** [comment]
Thank you for your reply. I converted.hic into mcool using hicConvertFormat, and then carried out TAD and compartment analysis. However, does this mcool need to be corrected? I did not correct it when I converted, and does it have any impact on the subsequent difference comparison.

For  loop analysis, the pair.gz is generated from juicer?

**Comment by ilead-cong** [comment]
Loop analysis can directly use .hic files. I think it is best for you to have a balance of .mcool file with cooler. Sometimes, different sequencing depths may affect the results.

**Comment by Zheng19w** [comment]
Thanks for your help, cooler balance cannot operate directly on mcool files. Is it okay to do it step by step？
cooler balance laiwu.matrix.mcool::/resolutions/1000
cooler balance laiwu.matrix.mcool::/resolutions/5000
cooler balance laiwu.matrix.mcool::/resolutions/10000
cooler balance laiwu.matrix.mcool::/resolutions/25000
cooler balance laiwu.matrix.mcool::/resolutions/50000
cooler balance laiwu.matrix.mcool::/resolutions/100000

**Comment by ilead-cong** [comment]
It is ok. You can balance it when you zoomfy cool to mcool with --balance next time

**Comment by Zheng19w** [comment]
谢谢您的帮助！预祝毕业快乐！！
