### ISSUE TITLE
hello，I notice that another github project—diff_TAD_type—was created by you，but i see no help manual there and could not find any way to figure out how to input files and outdir，and no way to contact with the developer，so i open this issue here，many thxs！

### ISSUE THREAD

**Issue by usernicai** [ilead-cong/hic_down#3]

**Comment by usernicai** [comment]
project—diff_TAD_type

**Comment by ilead-cong** [comment]
I'm very sorry, but for some reasons (currently in the process of integrating the tools, updating them to new versions, and integrating them into a toolset) I closed that project. If you need to use a previous version of the code for scientific research and need to obtain the corresponding documentation and sample files, please provide an email address that can receive the files, and I can package the relevant files and send them to you. More information about the new version of this tool will be released later.

**Comment by usernicai** [comment]
> I'm very sorry, but for some reasons (currently in the process of integrating the tools, updating them to new versions, and integrating them into a toolset) I closed that project. If you need to use a previous version of the code for scientific research and need to obtain the corresponding documentation and sample files, please provide an email address that can receive the files, and I can package the relevant files and send them to you. More information about the new version of this tool will be released later.
many thxs！ my email is luxunisgod123@gmail.com

**Comment by ilead-cong** [comment]
I'm very sorry. I've been too busy with work recently. This tool was developed during my master's degree and took a long time, so the email was sent late. Thank you very much for using this tool. If you have any questions about the documentation, please feel free to ask.
